### PR TITLE
Added new about field

### PR DESCRIPTION
**Pull request by rfdlp**

### CODE REVIEW

**Comment by toddhiestand** [comment]
@rafaeldalpra one small tweak: https://trello.com/c/UdHwaGia/123-add-new-sponsorships-field-to-api-and-plugin

**Comment by toddhiestand** [comment]
@rafaeldalpra awesome work :+1: :sunflower:

**Comment by toddhiestand** [comment]
@rafaeldalpra i delete the orange text color - somehow that showed up again. i squashed it for good.

**Comment by rfdlp** [comment]
:+1: thanks @toddhiestand  :)

**Pull request merged**
